name: Build and Deploy JupyterBook

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter-book ghp-import

      - name: Configure Git for ghp-import
        run: |
          git config --global user.name "jonathanferrari"
          git config --global user.email "jonathanferrari@berkeley.edu"

      - name: Build JupyterBook
        run: jb build --all modules

      - name: Deploy to GitHub Pages
        run: ghp-import -n -p -f modules/_build/html

      - name: Clean up build directory
        run: rm -rf modules/_build
