name: deploy-book

# Trigger on pushes to master or main branches
on:
  push:
    branches:
      - master
      - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3

      # Set up Python 3.11 and install dependencies
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -V  # Debug: Check Python version
          pip install -r requirements.txt
          pip list  # Debug: Check installed packages

      # Cache executed notebooks (if applicable)
      - name: Cache executed notebooks
        uses: actions/cache@v3
        with:
          path: modules/_build/.jupyter_cache
          key: jupyter-book-cache-${{ hashFiles('requirements.txt') }}

      # Debug: Ensure modules folder exists before build
      - name: Debug: Check initial modules structure
        run: ls -alR modules || echo "Modules folder does not exist"

      # Build the book from the modules folder
      - name: Build the book
        run: |
          set -e  # Exit immediately on failure
          jupyter-book --version  # Debug: Check jupyter-book version
          jupyter-book build --all modules || { echo "Build failed"; exit 1; }

      # Debug: List build output to verify files exist
      - name: Debug: List build output
        run: ls -alR modules/_build || echo "Build directory does not exist"

      # Debug: Verify HTML output exists before upload
      - name: Debug: Verify HTML output
        run: |
          if [ -d "modules/_build/html" ]; then
            echo "HTML output exists"
            ls -alR modules/_build/html
          else
            echo "HTML output is missing!"
            exit 1
          fi

      # Upload the generated HTML as an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: "modules/_build/html"
          artifact_name: pages
          if-no-files-found: error  # Explicitly fail if no files are found

      # Debug: Check uploaded artifacts
      - name: Debug: Check uploaded artifacts
        run: |
          echo "Listing artifacts in runner directory..."
          ls -alR /home/runner/work/_temp/_runner_file_commands || echo "Artifacts directory not found"

      # Deploy the uploaded artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: pages  # Ensure this matches the uploaded artifact name

      # Debug: Final check before cleanup
      - name: Debug: List final structure
        run: ls -alR modules/_build || echo "Build directory missing before cleanup"

      # Clean up the build directory
      - name: Clean up build directory
        run: rm -rf modules/_build
