name: deploy-book

# Trigger on pushes to master or main branches
on:
  push:
    branches:
      - master
      - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3

      # Set up Python 3.11 and install dependencies
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Cache executed notebooks (if applicable)
      - name: Cache executed notebooks
        uses: actions/cache@v3
        with:
          path: modules/_build/.jupyter_cache
          key: jupyter-book-cache-${{ hashFiles('requirements.txt') }}

      # Build the book from the modules folder
      - name: Build the book
        run: |
          jupyter-book build --all modules

      # Debug step: List the build output to verify files exist
      - name: List build output
        run: ls -al modules/_build/html

      # Upload the generated HTML as an artifact using v4 of the artifact action.
      # Explicitly naming it "pages" so the deploy step can find it.
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: "modules/_build/html"
          artifact_name: pages

      # Deploy the uploaded artifact to GitHub Pages.
      # (The deploy-pages action will look for the artifact with the name "pages".)
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: pages

      # Clean up the build directory (removes modules/_build but leaves modules/)
      - name: Clean up build directory
        run: rm -rf modules/_build
